export const deviceActionEnum = {
    SET_TYPES: 'SET_TYPES',
    SET_BRANDS: 'SET_BRANDS',
    SET_DEVICES: 'SET_DEVICES',
    SET_BASKET: 'SET_BASKET',
    SET_RATING: 'SET_RATING',
    SET_BASKET_COUNT: 'SET_BASKET_COUNT',
    SET_SELECTED_TYPE: 'SET_SELECTED_TYPE',
    SET_SELECTED_BRAND: 'SET_SELECTED_BRAND',
    SET_PAGE: 'SET_PAGE',
    SET_TOTAL_COUNT: 'SET_TOTAL_COUNT',
    SET_LIMIT: 'SET_LIMIT',
    SET_RATING_DEVICE: 'SET_RATING_DEVICE',
    SET_RATING_COUNT: 'SET_RATING_COUNT'
}